(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* :Title: Phylogenetic common functions *)
(* :Context: Phylogenetics` *)
(* :Author: Istv\[AAcute]n Zachar *)
(* :Email: istvan.zachar80@gmail.com *)
(* :Summary: Function declarations. *)
(* :Copyright: Copyright 2016-2017, Istv\[AAcute]n Zachar *)
(* :Package Version: 1.1 *)
(* :Mathematica Version: 11.0.0.0 *)
(* :Sources: *)
(* :Keywords: *)



(* ::Input::Initialization:: *)
BeginPackage["Phylogenetics`"];


$PhylogeneticsVersionNumber=1.1;

(* Declarations *)
{Leaf,Node,UniqueVerticesQ,TreeToGraph,Tree,Cladogram}; (* NOTE: Pre-declare these so that subpackages could use them. *)


Begin["`Private`"];


(* ::Input::Initialization:: *)
General::incomp="Some functions in the Phylogenetics` package are not compatible with \!\(\*
StyleBox[\"Mathematica\",\nFontSlant->\"Italic\"]\) versions predating 10.0.";
Which[
$VersionNumber<10,Message[General::incomp],
$VersionNumber<10.1,Quiet@{
MissingQ[expr_]:=MatchQ[expr,_Missing];
MinMax[expr_]:={Min@expr,Max@expr};
Subdivide[min_:0,max_:1,d_]:=min+(max-min) Range[0,d]/d;
},
$VersionNumber<10.2,Quiet@{
MissingQ[expr_]:=MatchQ[expr,_Missing];
}
];


(* ::Input::Initialization:: *)
mergeRules[opts__]:=Module[{flat=Flatten@{opts},new,old,ord},
new=DeleteDuplicates[First/@flat];
old=DeleteDuplicates[Reverse@flat,(First@#1===First@#2)&];
ord=First/@(new/.PositionIndex[First/@old]);
old[[ord]]
];


(* ::Input::Initialization:: *)
End[];

Protect[$PhylogeneticsVersionNumber];

EndPackage[];
